spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pgt_cloud?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: pgt123
  redis:
    host: 192.168.217.130
    port: 6379
    password:
    timeout: 3000
  jackson: #p配置时区
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://pgt123:pgt123@LagouCloudEurekaServerA:9300/eureka,http://pgt123:pgt123@LagouCloudEurekaServerB:9301/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
